#!/bin/sh

# Change the path of directory 
ENV_DIR=/home/user/.venv
export PROJECT_DIR=$(pwd)

function help_menu() {
    echo "Usage:"
    echo "  source-act [options] [environment_name]"
    echo
    echo "OPTIONS"
    echo "  --help\tshow help menu"
    echo "  -l, --list\tshow list of enironment names"
}

if [ $1 ];
then
    # echo "hello $1"
    if [[ $1 == "--list" || $1 == "-l" ]];
    then
        for i in $(eval "ls $ENV_DIR")
        do
            echo "$i"
        done

    elif [[ $1 == "--help" ]];
    then
        help_menu

    else
        ENV_FOUND=0
        for i in $(eval "ls $ENV_DIR")
        do
            if [[ $i == $1 ]];
            then
                ENV_FOUND=1
            fi
        done

        if [[ $ENV_FOUND == 1 ]];
        then
            source "$ENV_DIR/$1/bin/activate"
            echo "Loaded $1 -- ✅"
            echo "Current Directory is $PROJECT_DIR"
        else
            echo "Environment Not Found ❌"
        fi
    fi
else
    help_menu
fi
